services:
    david63.announceonindex.listener:
        class: david63\announceonindex\event\listener
        arguments:
            - '@config'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@content.visibility'
            - '@auth'
            - '@cache'
            - '@path_helper'
            - '@language'
        tags:
            - { name: event.listener }

    david63.announceonindex.admin.controller:
        class: david63\announceonindex\controller\admin_controller
        arguments:
            - '@config'
            - '@request'
            - '@template'
            - '@user'
            - '@language'
            - '@log'
